# Generated by Django 4.2.4 on 2024-01-04 13:15

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('campusVisit', '0002_alter_campusvisitrequest_datesfrom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='visitRequest',
            fields=[
                ('requestPK', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('valid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='alumini',
            fields=[
                ('aluminiPK', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('BitsId', models.CharField(max_length=13)),
                ('purposeOfVisit', models.CharField(max_length=254)),
                ('arrivialDate', models.DateField(verbose_name='From Date')),
                ('visitRequestForm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluminis', to='campusVisit.visitrequest')),
            ],
        ),
    ]
