# Generated by Django 4.2.4 on 2024-01-04 13:24

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('campusVisit', '0003_visitrequest_alumini'),
    ]

    operations = [
        migrations.CreateModel(
            name='guest',
            fields=[
                ('guestPK', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('relatedAlumini', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='campusVisit.alumini')),
            ],
        ),
        migrations.DeleteModel(
            name='campusVisitRequest',
        ),
    ]
