# Generated by Django 4.2.4 on 2024-01-04 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusVisit', '0004_guest_delete_campusvisitrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='alumini',
            new_name='alumni',
        ),
    ]
