# Generated by Django 4.2.7 on 2024-01-05 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campusVisit', '0006_rename_relatedalumini_guest_relatedalumni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='CompanyDesignation',
            field=models.CharField(default='NONE', max_length=254),
        ),
        migrations.AddField(
            model_name='alumni',
            name='arrivialDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='From Date'),
        ),
        migrations.AddField(
            model_name='alumni',
            name='comingFrom',
            field=models.CharField(default='NONE', max_length=254),
        ),
        migrations.AddField(
            model_name='alumni',
            name='currAddress',
            field=models.CharField(default='NONE', max_length=254),
        ),
        migrations.AddField(
            model_name='alumni',
            name='currCompany',
            field=models.CharField(default='NONE', max_length=254),
        ),
        migrations.AddField(
            model_name='alumni',
            name='departureDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='To Date'),
        ),
    ]
