# Generated by Django 4.2.7 on 2024-01-06 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusVisit', '0007_alumni_companydesignation_alumni_arrivialdatetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='aluminiPK',
            new_name='alumniPK',
        ),
    ]
