# Generated by Django 4.2.4 on 2024-01-22 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('campusVisit', '0008_rename_aluminipk_alumni_alumnipk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='relatedAlumni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='campusVisit.visitrequest'),
        ),
    ]
