# Generated by Django 4.2.4 on 2024-01-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusVisit', '0009_alter_guest_relatedalumni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='comingFrom',
        ),
        migrations.AddField(
            model_name='alumni',
            name='city',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='alumni',
            name='state',
            field=models.CharField(default='NONE', max_length=100),
        ),
        migrations.AddField(
            model_name='alumni',
            name='zip',
            field=models.IntegerField(default=0),
        ),
    ]
