# Generated by Django 4.2.4 on 2024-02-17 15:18

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campusVisit', '0013_alter_alumni_companydesignation_alter_alumni_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='arrivialDateTime',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='departureDateTime',
        ),
        migrations.AddField(
            model_name='alumni',
            name='arrivialDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='From Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumni',
            name='departureDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='To Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumni',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Invalid email address')]),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='zip',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Invalid email address')]),
        ),
    ]
