# Generated by Django 4.2.4 on 2024-02-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusVisit', '0014_remove_alumni_arrivialdatetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='zip',
            field=models.CharField(max_length=10),
        ),
    ]
