# Generated by Django 4.2.4 on 2024-02-17 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusVisit', '0015_alter_alumni_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='BitsId',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Enter a valid BITS ID', regex='^\\d{4}[GHDP][a-zA-Z]\\d{4}[a-zA-Z0-9]+$')]),
        ),
    ]
