# Generated by Django 4.2.4 on 2024-02-22 18:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusVisit', '0016_alter_alumni_bitsid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='BitsId',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Enter a valid BITS ID', regex='^\\d{4}[A-Z0-9]{2}[A-Z0-9]{2}\\d{4}[A-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='zip',
            field=models.PositiveIntegerField(),
        ),
    ]
