# Generated by Django 4.2.7 on 2024-02-26 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusVisit', '0017_alter_alumni_bitsid_alter_alumni_zip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='CompanyDesignation',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='arrivialDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='From Date'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='currAddress',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='currCompany',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='departureDate',
            field=models.DateTimeField(blank=True, null=True, verbose_name='To Date'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='purposeOfVisit',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='zip',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
