# Generated by Django 4.2.7 on 2024-02-27 05:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('campusVisit', '0018_alter_alumni_companydesignation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='CompanyDesignation',
            field=models.CharField(default='1', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumni',
            name='arrivialDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='From Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumni',
            name='city',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumni',
            name='country',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumni',
            name='currAddress',
            field=models.CharField(default='1', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumni',
            name='currCompany',
            field=models.CharField(default='1', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumni',
            name='departureDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='To Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alumni',
            name='purposeOfVisit',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='zip',
            field=models.PositiveIntegerField(),
        ),
    ]
