# Generated by Django 4.2.7 on 2024-04-08 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusVisit', '0019_alter_alumni_companydesignation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='departureDate',
        ),
    ]
