# Generated by Django 4.2.7 on 2024-04-09 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campusVisit', '0020_remove_alumni_departuredate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumni',
            old_name='arrivialDate',
            new_name='arrivalDate',
        ),
    ]
