# Generated by Django 4.2.7 on 2024-05-22 20:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusVisit', '0021_rename_arrivialdate_alumni_arrivaldate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='BitsId',
            field=models.CharField(error_messages={'blank': 'Bits ID field cannot be empty.'}, max_length=13, validators=[django.core.validators.RegexValidator(message='Enter a valid BITS ID', regex='^\\d{4}[A-Z0-9]{2}[A-Z0-9]{2}\\d{4}[A-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='CompanyDesignation',
            field=models.CharField(error_messages={'blank': 'Current Designation cannot be empty.'}, max_length=254),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='arrivalDate',
            field=models.DateTimeField(error_messages={'blank': 'Arrival Date cannot be empty.'}, verbose_name='From Date'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='city',
            field=models.CharField(error_messages={'blank': 'City cannot be empty.'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='country',
            field=models.CharField(error_messages={'blank': 'Country cannot be empty.'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='currAddress',
            field=models.CharField(error_messages={'blank': 'Current Address cannot be empty.'}, max_length=254),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='currCompany',
            field=models.CharField(error_messages={'blank': 'Current Company cannot be empty.'}, max_length=254),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='email',
            field=models.EmailField(error_messages={'blank': 'Email field cannot be empty.'}, max_length=254, validators=[django.core.validators.EmailValidator(message='You have entered an email address')]),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='firstName',
            field=models.CharField(error_messages={'blank': 'First Name field cannot be empty.'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='lastName',
            field=models.CharField(error_messages={'blank': 'Last Name field cannot be empty.'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='purposeOfVisit',
            field=models.CharField(error_messages={'blank': 'Purpose of visit cannot be empty.'}, max_length=254),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='state',
            field=models.CharField(error_messages={'blank': 'State cannot be empty.'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='zip',
            field=models.PositiveIntegerField(error_messages={'blank': 'ZIP cannot be empty.', 'invalid': 'ZIP must be a 6-digit number'}),
        ),
    ]
