# Generated by Django 4.2.7 on 2024-05-29 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campusVisit', '0022_alter_alumni_bitsid_alter_alumni_companydesignation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='BitsId',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator(message='Enter a valid BITS ID(20##XXPS####G)', regex='^\\d{4}[A-Z0-9]{2}[A-Z0-9]{2}\\d{4}[A-Z]+$')]),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='CompanyDesignation',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='arrivalDate',
            field=models.DateTimeField(verbose_name='From Date'),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='currAddress',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='currCompany',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='You have entered an invalid email address')]),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='firstName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='lastName',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='purposeOfVisit',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='state',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='zip',
            field=models.PositiveIntegerField(),
        ),
    ]
