# Generated by Django 4.2.7 on 2024-10-15 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SummerResearchApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=20)),
                ('contact_number', models.CharField(max_length=15)),
                ('project_objective', models.TextField()),
                ('past_research', models.TextField()),
                ('personal_statement', models.TextField()),
                ('cv', models.FileField(upload_to='cvs/')),
                ('acceptance_letter', models.FileField(upload_to='acceptance_letters/')),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='supporting_documents/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
