# Generated by Django 4.2.7 on 2024-10-15 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summerresearchapplication',
            options={'verbose_name': 'Summer Research Application', 'verbose_name_plural': 'Summer Research Applications'},
        ),
        migrations.AddField(
            model_name='summerresearchapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='summerresearchapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='summerresearchapplication',
            name='acceptance_letter',
            field=models.FileField(upload_to='summer_research_applications/acceptance_letters/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='summerresearchapplication',
            name='cv',
            field=models.FileField(upload_to='summer_research_applications/cv/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='summerresearchapplication',
            name='supporting_documents',
            field=models.FileField(blank=True, null=True, upload_to='summer_research_applications/supporting_documents/'),
        ),
    ]
