# Generated by Django 4.2.7 on 2024-10-16 09:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scholarship", "0002_alter_summerresearchapplication_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="summerresearchapplication",
            name="supporting_documents",
        ),
        migrations.CreateModel(
            name="SupportingDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="summer_research_applications/supporting_documents/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "doc", "docx"]
                            )
                        ],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supporting_documents",
                        to="scholarship.summerresearchapplication",
                    ),
                ),
            ],
        ),
    ]
