# Generated by Django 4.2.4 on 2023-11-27 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='coordi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('linkdn', models.TextField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='cordi',
        ),
        migrations.AddField(
            model_name='coordi',
            name='personDetails',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordi', to='base.person'),
        ),
    ]
