# Generated by Django 4.2.7 on 2023-11-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_coordi_person_delete_cordi_coordi_persondetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactDetail',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=254)),
                ('message', models.TimeField(max_length=508)),
            ],
        ),
    ]
