# Generated by Django 4.2.4 on 2023-11-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_contactdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactdetail',
            name='message',
            field=models.TextField(max_length=508),
        ),
    ]
