# Generated by Django 4.2.4 on 2023-11-27 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_contactdetail_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetail',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 11, 27, 16, 58, 7, 139513, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactdetail',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
