# Generated by Django 4.2.4 on 2024-02-04 14:26

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdetail',
            name='phoneNumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+91 8879706920', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
