# Generated by Django 4.2.4 on 2024-02-04 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_contactdetail_phonenumber'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='events',
            new_name='event',
        ),
    ]
