# Generated by Django 4.2.7 on 2024-02-28 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_event_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='created',
            new_name='date',
        ),
    ]
